#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     irseeker,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  motorC,          brush,         tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     scissorRight,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     scissorLeft,   tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     rightMotor,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     leftMotor,     tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    basketServo,          tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

//TJoystick joystick;

// NOTE: 0.781 is 100.0 / 128.0
short adjustValue(short inputValue)
{
    inputValue = (short)((inputValue * (abs(inputValue) / 128.0)) * 0.781);
    if (abs(inputValue) < 15)
    {
    	inputValue = 0; // Don't move unless outside range
    }

    return inputValue;
}

short adjustDrivingValue(short inputValue)
{
	short MAX_MOTOR_VAL = 90; // MAX percentage allowed
	inputValue = adjustValue(inputValue);
	if (inputValue > MAX_MOTOR_VAL)
	{
		inputValue = MAX_MOTOR_VAL;
	}
	else if (inputValue < -MAX_MOTOR_VAL)
	{
		inputValue = -MAX_MOTOR_VAL;
	}

	return inputValue;
}

void adjustDrivingPair(short& side1, short& side2)
{
	// NOTE: Only slow down the rates if trying to drive straight
	if (((side1 >= 0) && (side2 >= 0)) ||
		  ((side1 <= 0) && (side2 <= 0)))
		{
			side1 = adjustDrivingValue(side1);
			side2 = adjustDrivingValue(side2);
		}
}

task main()
{
	bool forwardIsFlipped = false;
	bool button3StillPressed = false;

  while (true)
  {
  //This is where the actual program begins
    getJoystickSettings(joystick);
    short leftMotorSpeed = joystick.joy1_y1;
    short rightMotorSpeed = joystick.joy1_y2;

    if (joystick.joy1_TopHat == 0)
    {
    	motor(scissorRight) = 80;
    	motor(brush) =100;
    }
    else if (joystick.joy1_TopHat == 4)
    {
    	motor(scissorRight) = -80;
    	motor(brush) =-100;
    }
    else
    {
    	motor(scissorRight) = 0;
    	motor(brush) = 0;
    }


  	short button3BeingPressed = joy1Btn(3);

    if (button3BeingPressed && !button3StillPressed)
    {
    	forwardIsFlipped = !forwardIsFlipped;
    	button3StillPressed = true;
    }
    else if (! button3BeingPressed) {
    	button3StillPressed = false;
    }

    if (forwardIsFlipped) {
    	short newLeft = rightMotorSpeed * -1;
    	short newRight = leftMotorSpeed * -1;

    	leftMotorSpeed = newLeft;
    	rightMotorSpeed = newRight;
    }

    adjustDrivingPair(leftMotorSpeed, rightMotorSpeed);
    //motor[leftMotor]  = leftMotorSpeed;
    //motor[rightMotor] = rightMotorSpeed;
    motor(leftMotor)  = leftMotorSpeed;
    motor(rightMotor) = rightMotorSpeed;
    //motor[motorE] = joystick.y2Pos;


	}
}
